### ISSUE TITLE
Formatting for footnotes

### ISSUE THREAD

**Issue by bmann** [patdryburgh/hitchens#10]
Jekyll (or specifically, kramdown) supports [footnotes](https://kramdown.gettalong.org/quickref.html#footnotes). It would be nice to have formatting for it.

Here's an example of the generated HTML from a footnote:

```
<div class="footnotes">
  <ol>
  <li id="fn:emailteam">
  <p>I wrote a <a href="https://speakerdeck.com/">presentation about email at companies</a> that I should revisit and add Missive to. <a href="#fnref:emailteam" class="reversefootnote">&#8617;</a></p>
  </li>
  </ol>
</div>
```

**Comment by patdryburgh** [comment]
@bmann I've added some formatting to the footnotes here: 

<img width="624" alt="screen shot 2018-10-18 at 9 49 25 pm" src="https://user-images.githubusercontent.com/751461/47198229-e1c48600-d31f-11e8-88dc-eeb0ddac3ec3.png">

Thanks for posting these issues for me!

**Comment by patdryburgh** [comment]
Not sure how I feel about the second divider… might be redundant.

**Comment by patdryburgh** [comment]
There, that's better:

<img width="655" alt="screen shot 2018-10-18 at 9 52 29 pm" src="https://user-images.githubusercontent.com/751461/47198269-218b6d80-d320-11e8-9391-84e46336dfc5.png">

**Comment by bmann** [comment]
So nice!
