### ISSUE TITLE
Valid JSON feeds

### ISSUE THREAD

**Issue by bmann** [patdryburgh/hitchens#11]
Pat, I used your JSON feeds as the basis for my own. Here are the gists I have for a ```feed.json``` (which has all the long form blog posts) and a ```micro.json``` (which has short posts only):

https://gist.github.com/bmann/38b54d893d506d2eb8bb8b325eafaccf

A note: right now, the micropub server I'm using defaults to setting category of short posts to "social", which I couldn't fix, so I just changed it in my Jekyll install.

Also, because of some of the rest of the Jekyll theme that I inherited, I purposefully don't include title in the micro feed.

Lastly, my theme / setup supports a date modified field, so I included that.

The validator for checking feeds is here: http://validator.jsonfeed.org/

(and apologies for not having a Pull Request for you, a lot of this stuff ends up being pretty blog specific)

**Comment by patdryburgh** [comment]
@bmann I've pushed a change that adds the missing curly bracket and commas in the JSON feed. You can see that the feed is now passing here: http://validator.jsonfeed.org/?url=https%3A%2F%2Fpatdryburgh.github.io%2Fhitchens%2Ffeed.json
