### ISSUE TITLE
Small Lighthouse audit details

### ISSUE THREAD

**Issue by jeanlucaslima** [patdryburgh/hitchens#12]
Just two items from Lighthouse that may impact score and performance could be added, they are:

* `font-auto` attribute to load text before the font loads
* `<meta>` description attribute (maybe with variable added to `_config.yml`

I added this in my instance, leaving it up as suggestion.

**Comment by patdryburgh** [comment]
Thanks for the feedback, @jeanlucaslima! The missing `<meta>` description was definitely an oversight (the default `_config.yml` file includes a `description` variable, it just wasn't included in the `default.html` template.

As for loading text before the font loads, I added the `font-display: auto` declaration to the `@font-face` rule set in `_fonts.scss`. I assume that is what you meant as I couldn't find any reference online to a `font-auto` attribute. If I'm incorrect, I welcome further insight into the issue.

One last question, I'm not sure what a “Lighthouse audit” is. Can you please fill me in?

Thanks again for the feedback! Hope you enjoy the theme :)

**Comment by jeanlucaslima** [comment]
@patdryburgh lighthouse is a tool that Google develops to "audit" pages in how fast they load and shows you a report on what points are not in best performance. That's also where I got the font-auto tip. You can try it on Google Chrome console, go to "Audits" tab and generate a new report.
