### ISSUE TITLE
Weird automatic Dark Mode on some Samsung devices

### ISSUE THREAD

**Issue by jeanlucaslima** [patdryburgh/hitchens#13]
Hey, I'm using this theme and got this weird situation, a friend uses Samsung and in their native browser this is how the site loads:

![image](https://user-images.githubusercontent.com/1311402/62939074-c93dc480-bda6-11e9-8390-ad0dece5f004.png)

Any ideas on how to prevent or to adapt to a dark theme?

**Comment by patdryburgh** [comment]
Hey @jeanlucaslima,

The theme does not currently support a dark mode. Judging from the screenshot, it appears that your friend has some sort of “invert colours” setting turned on in their phone's settings.

Can you please have them load https://patdryburgh.github.io/hitchens/ and publish a screenshot of what comes up? Thanks!

—Pat
